#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Settings of tmux
export PATH=$PATH:~/.local/bin

# Settings of pure theme
fpath+=$HOME/.zsh/pure

# Settings of pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Settings of clipboard through X11 forwarding
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
