[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	let g:airline#extensions#tabline#enabled = 1
	let g:airline_powerline_fonts = 1
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#ale#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
