[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
	let g:ale_sign_error = 'E'
	let g:ale_sign_warning = 'W'
	let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
	nmap <silent> <C-k> <Plug>(ale_previous_wrap)
	nmap <silent> <C-j> <Plug>(ale_next_wrap)
	let g:ale_set_loclist = 0
	let g:ale_set_quickfix = 1
	let g:ale_open_list = 1
	let g:ale_echo_cursor = 0
	highlight ALEWarning ctermbg=Yellow
	highlight ALEWarning ctermfg=Black
	highlight ALEError ctermbg=Red
	highlight ALEError ctermfg=Black
'''
