set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# Settings of Powerline
run-shell "/Users/taiki_okano/.pyenv/shims/powerline-daemon -q"
run-shell "/Users/taiki_okano/.pyenv/shims/powerline-config tmux setup"


# Settings of vim-copy-mode
setw -g mode-keys vi
bind-key    -T copy-mode-vi v     send-keys -X begin-selection
bind-key    -T copy-mode-vi y     send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key    -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Settings of pane changing (Vim key bind)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# Settings of pane size changing
bind H resize-pane -L 30
bind J resize-pane -D 30
bind K resize-pane -U 30
bind L resize-pane -R 30

# Settings of the behavior when a new pain is opened
bind % split-window -h -c '#{pane_current_path}'
bind \" split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'
