set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# Settings of Powerline
run-shell "powerline-daemon -q"
source "/Users/taiki_okano/.local/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf"

# Settings of vim-copy-mode
setw -g mode-keys vi
bind-key    -T copy-mode-vi v     send-keys -X begin-selection
bind-key    -T copy-mode-vi y     send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key    -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Settings of pane changing (Vim key bind)
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Settings of pane size changing
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Settings of the behavior when a new pain is opened
bind % split-window -h -c '#{pane_current_path}'
bind \" split-window -v -c '#{pane_current_path}'
