#!/bin/bash

# Clone TPM (tmux plugin manager)
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
	tmux source ~/.tmux.conf
fi

# Install fzf
if ! command -v fzf &> /dev/null; then
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install
fi

# Install Ripgrep, bat, and fd
if ! command -v rg &> /dev/null; then
	curl -sS https://webi.sh/rg | sh
	[ -f "$HOME/.config/envman/PATH.env" ] && source ~/.config/envman/PATH.env
fi

if ! command -v fd &> /dev/null; then
	curl -sS https://webi.sh/fd | sh
	[ -f "$HOME/.config/envman/PATH.env" ] && source ~/.config/envman/PATH.env
fi

if ! command -v bat &> /dev/null; then
	curl -sS https://webi.sh/bat | sh
	[ -f "$HOME/.config/envman/PATH.env" ] && source ~/.config/envman/PATH.env
fi

# Install Oh-My-Zsh with plugins
ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
if [ ! -d "${ZSH_CUSTOM}" ]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
fi
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
fi
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-vi-mode" ]; then
    git clone https://github.com/jeffreytse/zsh-vi-mode "$ZSH_CUSTOM/plugins/zsh-vi-mode"
fi

# Install pyenv
if [ ! -d "$HOME/.pyenv" ]; then
	curl https://pyenv.run | bash
fi

# Install rbenv
if [ ! -d "$HOME/.rbenv" ]; then
	git clone https://github.com/rbenv/rbenv.git ~/.rbenv
	~/.rbenv/bin/rbenv init
fi

# OS specific
if [ $(uname -s) == "Linux" ]; then
	if [ $(uname -m) == "aarch64" ]; then
		# Linux aarch64

		# Neovim
		if ! command -v nvim &> /dev/null; then
			curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-arm64.tar.gz
			tar xzf nvim-linux-arm64.tar.gz
			mkdir -p $HOME/.local/nvim
			mv nvim-linux-arm64/* $HOME/.local/nvim/
			ln -sf $HOME/.local/nvim/bin/nvim $HOME/.local/bin/nvim
			rm -r nvim-linux-arm64
		fi

	elif [ $(uname -m) == "x86_64" ]; then
		# Linux amd64
		
		# Neovim
		if ! command -v nvim &> /dev/null; then
			curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
			tar xzf nvim-linux-x86_64.tar.gz
			mkdir -p $HOME/.local/nvim
			mv nvim-linux-x86_64/* $HOME/.local/nvim/
			ln -sf $HOME/.local/nvim/bin/nvim $HOME/.local/bin/nvim
			rm -r nvim-linux-x86_64
		fi

	fi

elif [ $(uname -s) == "Darwin" ]; then
	# macOS aarch64
	
	# Neovim
	if ! command -v nvim &> /dev/null; then
		curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-macos-arm64.tar.gz
		tar xzf nvim-macos-arm64.tar.gz
		mkdir -p $HOME/.local/nvim
		mv nvim-macos-arm64/* $HOME/.local/nvim/
		ln -sf $HOME/.local/nvim/bin/nvim $HOME/.local/bin/nvim
		rm -r nvim-macos-arm64
	fi

fi

